version: '3.8'
services:

  mainapp:
    image: ekosinskiy/k8s-demo-main:v1
#    build:
#      context: ./main
    ports:
    - "8100:80"

    volumes:
    - type: bind
      source: ./main
      target: /var/www/html

    networks:
      - knet

    tty: true

  producer:
    image: ekosinskiy/k8s-demo-producer:v1
#    build:
#      context: ./producer
#    volumes:
#      - type: bind
#        source: ./producer
#        target: /var/www/html

    networks:
      - knet
    command: ["php", "/var/www/html/index.php"]
    tty: true

  producer2:
    build:
      context: ./producer
    volumes:
      - type: bind
        source: ./producer
        target: /var/www/html

    networks:
      - knet
    command: ["php", "/var/www/html/index.php"]
    tty: true

#  consumer:
#    build:
#      context: ./consumer
#    networks:
#      - knet

  redis:
    image: redis:5-alpine
    networks:
      - knet

networks:
  knet:
    external: true
    driver: "bridge"
