---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: producer
  name: producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
    spec:
      containers:
        - image: ekosinskiy/k8s-demo-producer:v3
          name: producer
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: producer
  name: producer
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: producer
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: redis
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - image: redis
          name: redis
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis
  name: redis
spec:
  ports:
    - port: 6379
      protocol: TCP
      targetPort: 6379
  selector:
    app: redis
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: main
  name: main
spec:
  replicas: 1
  selector:
    matchLabels:
      app: main
  template:
    metadata:
      labels:
        app: main
    spec:
      containers:
        - image: ekosinskiy/k8s-demo-main:v1
          name: main
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: main
  name: main
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: main
  type: NodePort



